### ISSUE TITLE
Get public key gets stuck without any error

### ISSUE THREAD

**Issue by t4sk** [Mysolarikk/zymkey-test#1]
Script ran for about 40 minutes (got public key 453 times) before getting stuck. No errors were thrown

### Last logs ###
```shell
Jun 27 13:50:50 raspberrypi start.sh[1361]: start
Jun 27 13:50:50 raspberrypi start.sh[1361]: Got public key
Jun 27 13:50:50 raspberrypi start.sh[1361]: done 0:00:00.086620
Jun 27 13:50:50 raspberrypi start.sh[1361]: ('i', 452)
Jun 27 13:50:55 raspberrypi start.sh[1361]: start
Jun 27 13:50:55 raspberrypi start.sh[1361]: Got public key
Jun 27 13:50:55 raspberrypi start.sh[1361]: done 0:00:00.086637
Jun 27 13:50:55 raspberrypi start.sh[1361]: ('i', 453)
Jun 27 13:51:00 raspberrypi start.sh[1361]: start
```

**Comment by t4sk** [comment]
Signing also stopped after about an hour

```
Jul 01 13:53:15 raspberrypi start.sh[17780]: done 0:00:00.126135
Jul 01 13:53:15 raspberrypi start.sh[17780]: ('i', 726)
Jul 01 13:53:20 raspberrypi start.sh[17780]: start
```

**Comment by t4sk** [comment]
Restarting raspberry pi
```shell
Jul 03 13:01:25 raspberrypi start.sh[640]: zkifc send error: Broken pipe
Jul 03 13:01:25 raspberrypi start.sh[640]: ('main error', AssertionError('bad return code -1',))
Jul 03 13:01:25 raspberrypi start.sh[640]: ('i', 1805)
```

**Comment by t4sk** [comment]
executing script without starting virtualenv

```
.ZymkeyLibraryError: unable to find libzk_app_utils.so
```

**Comment by t4sk** [comment]
script runs without any problem (more than 2 hours) with virtualenv

**Comment by t4sk** [comment]
got stuck after 5 hours even with timeout.

no other systemd service was running

**Comment by t4sk** [comment]
one solution is to restart systemd service periodically

**Comment by lpninja** [comment]
- Make sure the power supply is always a quality 2.5A.
- Use high quality dedicated USB keys for DB writes and re-write. Do not use SD cards for any DB work.

Reference from Scott @Zymbit. https://community.zymbit.com/t/getting-public-key-gets-stuck-without-any-error/595/16

**Comment by t4sk** [comment]
won't be able to get public key with data logger is running

**Comment by lpninja** [comment]
Ok then close this issue I think.
